"""`adaf gha init` — materialise the CLI-owned reusable composite actions into a consuming repo.

The two `adaf-*` composite actions — `adaf-ci` (the shared per-job bootstrap: GCP auth, the uv/dbt
env, and optional defer-state/manifest artifact restore) and `adaf-cleanup` (PR-namespaced dataset
teardown) — are the shared building blocks the per-product workflows (`adaf gha create`) call. The
per-product workflow itself is a multi-job graph (setup / checks / dbt-build / report) that calls the
bootstrap action once per job. `gha init` also ships the two repo-level workflows those actions back:
`adaf-reusable.yml` (the shared job graph the per-product callers `uses:`) and `adaf-cleanup.yml` (the
PR-close trigger that invokes the `adaf-cleanup` action). Their canonical source lives WITH the CLI as
package data (`adaf/gha/assets/{actions,workflows}/...`), so a repo that vendors adaf can re-materialise
them with one command instead of hand-copying — mirroring how `gha create` clones the workflow template.

Each file is written with a version-stamped banner (``# adaf:managed version=<X.Y.Z> ...``) inserted at
the top (after any shebang). That banner is the **version check**: a later `gha init` reads the version
out of the already-deployed file and, when it differs from the packaged CLI version, reports the drift
and refuses to clobber without ``--force`` — the same skip-unless-forced contract as `gha create`.
"""

# Standard Library
import argparse
import logging
import re
import sys
from pathlib import Path

# Local
from adaf import __version__, config, report

log = logging.getLogger(__name__)

# Greppable marker that tags a file as managed by `gha init`; the version follows as `version=<X.Y.Z>`.
MANAGED_SENTINEL = "adaf:managed"
_VERSION_RE = re.compile(rf"{re.escape(MANAGED_SENTINEL)} version=(?P<version>\S+)")

# Suffixes that take an HTML-style comment; everything else gets a `#`-style line comment.
_HTML_COMMENT_SUFFIXES = {".md", ".html", ".xml"}


def _fences(suffix: str) -> tuple[str, str]:
    """The (open, close) comment delimiters for a file suffix. `#`-style for code/YAML/shell, `<!-- -->`
    for markup. Unknown suffixes fall back to `#` (the safe default for the YAML/shell/py files we ship)."""
    if suffix.lower() in _HTML_COMMENT_SUFFIXES:
        return "<!-- ", " -->"
    return "# ", ""


def banner(version: str, suffix: str) -> str:
    """The single managed-by header line for a file of the given suffix."""
    open_, close = _fences(suffix)
    body = (
        f"{MANAGED_SENTINEL} version={version} — generated by `adaf gha init`; edits are overwritten on the next sync"
    )
    return f"{open_}{body}{close}"


def with_header(text: str, suffix: str, version: str) -> str:
    """Return ``text`` with the managed banner prepended — placed AFTER a shebang line if present, so
    `#!/usr/bin/env ...` stays line 1 and the script remains executable."""
    line = banner(version, suffix)
    lines = text.split("\n")
    if lines and lines[0].startswith("#!"):
        return "\n".join([lines[0], line, *lines[1:]])
    return f"{line}\n{text}"


def managed_version(text: str) -> str | None:
    """Extract the version stamped in a deployed file's managed banner, or ``None`` if unmanaged.

    Only the first few lines are scanned so a `version=` token elsewhere in the body can't be misread."""
    head = "\n".join(text.split("\n")[:5])
    m = _VERSION_RE.search(head)
    return m.group("version") if m else None


def _asset_files(source: Path) -> list[Path]:
    """Every file under the packaged actions asset tree, sorted for deterministic output."""
    return sorted(p for p in source.rglob("*") if p.is_file())


def _deploy_tree(source: Path, dest_dir: Path, *, force: bool, color: bool) -> tuple[int, int, int, int]:
    """Version-stamp + write every file under ``source`` into ``dest_dir``. Returns
    ``(created, updated, current, stale)``. Existing files are skipped unless ``force``; a skip whose
    deployed version differs from the CLI version is reported as drift (fix: re-run with --force)."""
    created = updated = current = stale = 0
    for src in _asset_files(source):
        dest = dest_dir / src.relative_to(source)
        existed = dest.exists()
        payload = with_header(src.read_text(encoding="utf-8"), src.suffix, __version__)

        if existed and not force:
            deployed = managed_version(dest.read_text(encoding="utf-8"))
            if deployed == __version__:
                current += 1
                log.info("gha init: %s already at v%s", dest, __version__)
                continue
            stale += 1
            was = f"v{deployed}" if deployed else "unmanaged"
            report.render_headline(
                f"drift: {dest} is {was}, CLI is v{__version__} — pass --force to overwrite",
                color=color,
                severity="warn",
            )
            continue

        verb = "updated" if existed else "created"
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(payload, encoding="utf-8")
        updated += int(existed)
        created += int(not existed)
        log.debug("gha init: %s %s (v%s)", verb, dest, __version__)
        report.render_headline(f"{verb} {dest}", color=color, severity="ok")
    return created, updated, current, stale


def deploy_workflows(workflows_dir: Path, *, force: bool, color: bool) -> tuple[int, int, int, int]:
    """Deploy the packaged reusable workflow asset tree into ``workflows_dir``. Shared by `gha init` and
    `gha create`, so a freshly-created per-product caller always has its `adaf-reusable.yml` dependency."""
    return _deploy_tree(config.GHA_WORKFLOWS_ASSETS_DIR, workflows_dir, force=force, color=color)


def cmd_init(args: argparse.Namespace) -> int:
    """Materialise the CLI-owned reusable pieces, version-stamping each file: the `adaf-*` composite
    actions into ``--actions-dir`` AND the reusable workflow into ``--workflows-dir`` (a reusable
    workflow can't live under actions/ — GitHub requires `.github/workflows/`)."""
    color = report.should_colorize(args.color, sys.stdout)
    actions_src: Path = config.GHA_ACTIONS_ASSETS_DIR
    workflows_src: Path = config.GHA_WORKFLOWS_ASSETS_DIR
    if not actions_src.is_dir():
        raise FileNotFoundError(f"packaged actions assets not found at '{actions_src}'")
    if not workflows_src.is_dir():
        raise FileNotFoundError(f"packaged workflow assets not found at '{workflows_src}'")

    actions_dir: Path = config.under_root(args.actions_dir)  # type: ignore[assignment]
    workflows_dir: Path = config.under_root(args.workflows_dir)  # type: ignore[assignment]
    c = u = cur = stale = 0
    for src, dst in ((actions_src, actions_dir), (workflows_src, workflows_dir)):
        dc, du, dcur, ds = _deploy_tree(src, dst, force=args.force, color=color)
        c, u, cur, stale = c + dc, u + du, cur + dcur, stale + ds

    summary = f"gha init v{__version__}: {c} created, {u} updated, {cur} current, {stale} stale"
    report.render_headline(summary, color=color, severity="warn" if stale else "ok")
    return 0
