name: ADAF Cleanup Workflow

on:
  pull_request:
    branches: [main]
    types: [closed]

  workflow_dispatch:
    inputs:
      target:
        required: true
        type: string
      pr-number:
        required: true
        type: string
      dry-run:
        required: false
        type: boolean
        default: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  id-token: write # required for WIF (google-github-actions/auth)

env:
  WIF_PROVIDER: ${{ vars.WIF_PROVIDER }}
  WIF_SA: 'dbt-test@dbt-test-jaffleshop.iam.gserviceaccount.com'
  DBT_PR_NUMBER: ${{ inputs.pr-number || github.event.pull_request.number }}
  DBT_AUTH_METHOD: oauth
  DBT_TARGET: ${{ inputs.target || 'test' }}

jobs:
  adaf-cleanup:
    name: ADAF Cleanup
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: ${{ env.WIF_PROVIDER }}
          service_account: ${{ env.WIF_SA }}

      - name: Set up gcloud CLI
        uses: "google-github-actions/setup-gcloud@v3"
        with:
          version: "573.0.0"
          cache: true

      - name: Run ADAF Cleanup
        uses: ./.github/actions/adaf-cleanup
        with:
          target: ${{ env.DBT_TARGET }}
          pr-number: ${{ env.DBT_PR_NUMBER }}
          dry-run: ${{ inputs.dry-run }}
